name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - actions/trigger/CompatHelper

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; pkg"add CompatHelper#13ec956c066a2a21c1f69a7bb1f9f530ae6e1b7d"'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          julia -e '
          using CompatHelper;
          CompatHelper.main() do;
              run(`julia --project=test/environments/main -e "import Pkg; Pkg.instantiate(); Pkg.update()"`);
              run(`julia --project=docs -e "import Pkg; Pkg.instantiate(); Pkg.update()"`);
          end
          '
